(()=>{function R(u){if(!u)return null;let f={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11,jan:0,feb:1,mar:2,apr:3,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11,"1\u6708":0,"2\u6708":1,"3\u6708":2,"4\u6708":3,"5\u6708":4,"6\u6708":5,"7\u6708":6,"8\u6708":7,"9\u6708":8,"10\u6708":9,"11\u6708":10,"12\u6708":11,"1\uC6D4":0,"2\uC6D4":1,"3\uC6D4":2,"4\uC6D4":3,"5\uC6D4":4,"6\uC6D4":5,"7\uC6D4":6,"8\uC6D4":7,"9\uC6D4":8,"10\uC6D4":9,"11\uC6D4":10,"12\uC6D4":11},d=u.match(/(\d{4})/);if(!d)return null;let E=parseInt(d[1],10),g=null,m=u.match(/(\d{1,2})[月월]/);if(m)g=parseInt(m[1],10)-1;else{let L=u.toLowerCase();for(let[y,v]of Object.entries(f))if(L.includes(y)){g=v;break}}return g===null?null:new Date(E,g,1)}function A(u,f=2,d=new Date){let E=R(u);if(!E)return!1;let g=new Date(d.getFullYear(),d.getMonth()-f,1);return E>=g}var l=typeof browser<"u"?browser:chrome;document.addEventListener("DOMContentLoaded",()=>{let u=document.getElementById("profileCount"),f=document.getElementById("profileList"),d=document.getElementById("locationStatsList"),E=document.getElementById("exportBtn"),g=document.getElementById("copyBtn"),m=document.getElementById("clearBtn"),L=document.getElementById("autoQueryToggle"),y=document.getElementById("locationFilter"),v=document.querySelectorAll(".tab-btn"),M=document.getElementById("profilesTab"),I=document.getElementById("locationsTab"),b={},x="",w=!1,B="profiles";v.forEach(e=>{e.addEventListener("click",()=>{let n=e.dataset.tab;B=n,v.forEach(t=>t.classList.remove("active")),e.classList.add("active"),M.classList.toggle("active",n==="profiles"),I.classList.toggle("active",n==="locations"),n==="locations"&&P()})}),l.storage.local.get(["autoQueryEnabled"]).then(e=>{let n=e.autoQueryEnabled!==!1;L.checked=n}),L.addEventListener("change",()=>{let e=L.checked;l.storage.local.set({autoQueryEnabled:e}),l.tabs.query({active:!0,currentWindow:!0}).then(n=>{var t;(t=n[0])!=null&&t.id&&l.tabs.sendMessage(n[0].id,{type:"AUTO_QUERY_CHANGED",enabled:e})})});function U(){document.querySelectorAll("[data-i18n]").forEach(e=>{let n=l.i18n.getMessage(e.dataset.i18n);n&&(e.textContent=n)}),document.querySelectorAll("[data-i18n-title]").forEach(e=>{let n=l.i18n.getMessage(e.dataset.i18nTitle);n&&(e.title=n)})}U();let D=l.i18n.getMessage("filterPlaceholder")||"Filter by location...";y.placeholder=D,y.addEventListener("input",e=>{x=e.target.value,w=!1,T()});function S(){l.storage.local.get(["profileCache"]).then(e=>{b=e.profileCache||{};let n=Object.keys(b).length;u.textContent=n,T()}).catch(e=>{console.error("Failed to load profiles:",e)})}function T(){let e=Object.entries(b);if(w)e=e.filter(([,t])=>!t.location);else if(x){let t=x.toLowerCase();e=e.filter(([,c])=>c.location&&c.location.toLowerCase().includes(t))}if(e.length===0){let t=x?l.i18n.getMessage("noLocation")||"No location":l.i18n.getMessage("emptyState")||`No profiles extracted yet.
Browse Threads to capture profile info.`;f.textContent="";let c=document.createElement("div");c.className="empty-state";let C=document.createElement("div");C.className="empty-state-icon",C.textContent="\u{1F50D}";let o=document.createElement("div");o.className="empty-state-text",t.split(`
`).forEach((r,s)=>{s>0&&o.appendChild(document.createElement("br")),o.appendChild(document.createTextNode(r))}),c.appendChild(C),c.appendChild(o),f.appendChild(c);return}e.sort((t,c)=>(c[1].timestamp||0)-(t[1].timestamp||0));let n=l.i18n.getMessage("newUser")||"NEW";f.textContent="",e.forEach(([t,c])=>{let C=A(c.joined),o=document.createElement("div");if(o.className="profile-item",o.setAttribute("data-username",t),c.profileImage){let i=document.createElement("img");i.src=c.profileImage,i.className="profile-avatar",i.alt=t,o.appendChild(i)}else{let i=document.createElement("div");i.className="profile-avatar",o.appendChild(i)}let a=document.createElement("div");a.className="profile-info";let r=document.createElement("div");if(r.className="profile-name",r.textContent=c.displayName||t,C){let i=document.createElement("span");i.className="new-user-tag",i.textContent=`[${n}]`,r.appendChild(i)}let s=document.createElement("div");s.className="profile-meta",s.textContent=`@${t}`,c.location&&(s.appendChild(document.createTextNode(" \u2022 \u{1F4CD} ")),s.appendChild(document.createTextNode(c.location))),a.appendChild(r),a.appendChild(s),o.appendChild(a),o.addEventListener("click",()=>{l.tabs.create({url:`https://www.threads.com/@${t}`})}),f.appendChild(o)})}E.addEventListener("click",()=>{let e=JSON.stringify(b,null,2),n=new Blob([e],{type:"application/json"}),t=URL.createObjectURL(n),c=document.createElement("a");c.href=t,c.download=`threads-profiles-${new Date().toISOString().split("T")[0]}.json`,c.click(),URL.revokeObjectURL(t),N(l.i18n.getMessage("exportSuccess")||"Exported successfully!")}),g.addEventListener("click",async()=>{let e=JSON.stringify(b,null,2);try{await navigator.clipboard.writeText(e),N(l.i18n.getMessage("copySuccess")||"Copied to clipboard!")}catch(n){console.error("Failed to copy:",n),N(l.i18n.getMessage("copyFailed")||"Failed to copy",!0)}}),m.addEventListener("click",()=>{if(confirm(l.i18n.getMessage("confirmClear")||"Are you sure you want to clear all cached profiles?")){let e=m.textContent;m.textContent="\u23F3 "+(l.i18n.getMessage("clearing")||"Clearing..."),m.disabled=!0,l.storage.local.set({profileCache:{},userIdCache:{}}).then(()=>{S(),m.textContent=e,m.disabled=!1,N(l.i18n.getMessage("cacheCleared")||"\u2713 Cache cleared successfully!")}).catch(n=>{console.error("Failed to clear cache:",n),m.textContent=e,m.disabled=!1,N(l.i18n.getMessage("clearFailed")||"Failed to clear cache",!0)})}});function N(e,n=!1){let t=document.createElement("div");t.style.cssText=`
      position: fixed;
      bottom: 20px;
      left: 50%;
      transform: translateX(-50%);
      padding: 10px 20px;
      background: ${n?"#ef4444":"#10b981"};
      color: white;
      border-radius: 8px;
      font-size: 14px;
      font-weight: 500;
      z-index: 10000;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
      opacity: 0;
      transition: opacity 0.3s ease;
    `,t.textContent=e,document.body.appendChild(t),setTimeout(()=>{t.style.opacity="1"},10),setTimeout(()=>{t.style.opacity="0",setTimeout(()=>t.remove(),300)},2500)}function P(){let e=Object.entries(b),n={},t=0;e.forEach(([,o])=>{if(o.location){let a=o.location.trim();n[a]=(n[a]||0)+1}else t++});let c=Object.entries(n).sort((o,a)=>a[1]-o[1]);if(c.length===0){let o=l.i18n.getMessage("noLocationStats")||`No location data yet.
Browse Threads to capture profile locations.`;d.textContent="";let a=document.createElement("div");a.className="empty-state";let r=document.createElement("div");r.className="empty-state-icon",r.textContent="\u{1F4CD}";let s=document.createElement("div");s.className="empty-state-text",o.split(`
`).forEach((p,h)=>{h>0&&s.appendChild(document.createElement("br")),s.appendChild(document.createTextNode(p))}),a.appendChild(r),a.appendChild(s),d.appendChild(a);return}let C=c[0][1];if(d.textContent="",c.forEach(([o,a])=>{let r=a/C*100,s=document.createElement("div");s.className="location-stat-item",s.setAttribute("data-location",o);let i=document.createElement("div");i.className="location-info";let p=document.createElement("div");p.className="location-content";let h=document.createElement("div");h.className="location-name",h.textContent=o;let j=document.createElement("div");j.className="location-bar";let k=document.createElement("div");k.className="location-bar-fill",k.style.width=`${r}%`,j.appendChild(k),p.appendChild(h),p.appendChild(j),i.appendChild(p);let F=document.createElement("span");F.className="location-count",F.textContent=a,s.appendChild(i),s.appendChild(F),s.addEventListener("click",()=>{w=!1,x=o,y.value=o,B="profiles",v.forEach(O=>O.classList.toggle("active",O.dataset.tab==="profiles")),M.classList.add("active"),I.classList.remove("active"),T()}),d.appendChild(s)}),t>0){let o=l.i18n.getMessage("noLocation")||"No location",a=document.createElement("div");a.className="location-stat-item",a.setAttribute("data-location",""),a.style.opacity="0.6";let r=document.createElement("div");r.className="location-info";let s=document.createElement("div");s.className="location-content";let i=document.createElement("div");i.className="location-name",i.textContent=o,s.appendChild(i),r.appendChild(s);let p=document.createElement("span");p.className="location-count",p.textContent=t,a.appendChild(r),a.appendChild(p),a.addEventListener("click",()=>{w=!0,x="",y.value="",B="profiles",v.forEach(h=>h.classList.toggle("active",h.dataset.tab==="profiles")),M.classList.add("active"),I.classList.remove("active"),T()}),d.appendChild(a)}}S(),l.runtime.onMessage.addListener(e=>{e.type==="PROFILE_INFO_EXTRACTED"&&S()})});})();
//# sourceMappingURL=popup.js.map
